\echo Running Q1...
\ir queries/01_q1_active_reservations_per_hotel_chain.sql

\echo Running Q2...
\ir queries/02_q2_customers_above_average_spend.sql

\echo Running Q3...
\ir queries/03_q3_available_rooms_with_filters.sql

\echo Running Q4...
\ir queries/04_q4_employee_performance_summary.sql

\echo Running required view query A...
\ir queries/07_view_available_rooms_per_area.sql

\echo Running required view query B...
\ir queries/08_view_hotel_capacity_aggregate.sql

\echo Running Q5...
\ir queries/09_q5_employees_at_hotel_3.sql
